---
postgresql_version: 13
postgresql_db: sonarqube
postgresql_user: sonar
postgresql_password: sonar_password
sonarqube_version: 9.6.1.59531
sonarqube_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
