---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java (Jenkins dependency)
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download Jenkins repository key
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    dest: /etc/apt/trusted.gpg.d/jenkins.asc

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/jenkins.asc] http://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Update apt cache (again)
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes
