---
- name: Install required dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - openjdk-11-jdk
    - unzip

- name: Download SonarQube
  get_url:
    url: "{{ sonarqube_download_url }}"
    dest: /tmp/sonarqube-{{ sonarqube_version }}.zip

- name: Unzip SonarQube
  unarchive:
    src: /tmp/sonarqube-{{ sonarqube_version }}.zip
    dest: /opt
    remote_src: yes

- name: Create symbolic link for SonarQube
  file:
    src: /opt/sonarqube-{{ sonarqube_version }}
    dest: /opt/sonarqube
    state: link

- name: Create SonarQube user
  user:
    name: sonar
    home: /opt/sonarqube
    shell: /bin/bash
    system: yes

- name: Change ownership of SonarQube directories
  file:
    path: /opt/sonarqube-{{ sonarqube_version }}
    state: directory
    owner: sonar
    group: sonar
    recurse: yes

- name: Configure SonarQube database settings
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: "^#sonar.jdbc.username="
    line: "sonar.jdbc.username={{ postgresql_user }}"
    state: present

- name: Configure SonarQube database settings
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: "^#sonar.jdbc.password="
    line: "sonar.jdbc.password={{ postgresql_password }}"
    state: present

- name: Configure SonarQube database settings
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: "^#sonar.jdbc.url="
    line: "sonar.jdbc.url=jdbc:postgresql://localhost:5432/{{ postgresql_db }}"
    state: present

- name: Create systemd service for SonarQube
  copy:
    dest: /etc/systemd/system/sonarqube.service
    content: |
      [Unit]
      Description=SonarQube service
      After=network.target

      [Service]
      Type=simple
      User=sonar
      Group=sonar
      ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
      ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
      LimitNOFILE=65536
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start SonarQube service
  systemd:
    name: sonarqube
    enabled: yes
    state: started
    daemon_reload: yes
