---
- name: Ensure dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - tar

- name: Download OpenShift CLI
  get_url:
    url: "{{ oc_cli_download_url }}"
    dest: /tmp/openshift-client-linux.tar.gz

- name: Extract OpenShift CLI
  unarchive:
    src: /tmp/openshift-client-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Ensure OpenShift CLI binaries are executable
  file:
    path: /usr/local/bin/{{ item }}
    mode: '0755'
    state: file
  loop:
    - oc
    - kubectl

- name: Verify OpenShift CLI installation
  command: oc version
  register: oc_version_result
  changed_when: false

- debug:
    msg: "OpenShift CLI version: {{ oc_version_result.stdout }}"
